routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'can:admin-panel']], function() {
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/banner', 'BannerController', ['as' => 'admin']);
    Route::resource('/advantage', 'AdvantageController', ['as' => 'admin']);
    Route::resource('/price', 'PriceController', ['as' => 'admin']);
    Route::resource('/service', 'ServiceController', ['as' => 'admin']);
    Route::group(['prefix' => 'user_managment', 'namespace' => 'UserManagment'], function() {
        Route::resource('/user', 'UserController', ['as' => 'admin.user_managment']);
    });
    Route::group(['prefix' => 'menu', 'namespace' => 'AdminMenu'], function() {
        Route::get('/{model?}', 'AdminMenuController@index')->name('admin.menu.index');
        Route::post('/{model?}', 'AdminMenuController@store')->name('admin.menu.store');
        Route::get('/{model?}/create', 'AdminMenuController@create')->name('admin.menu.create');
        Route::put('/{model?}/{item_id?}', 'AdminMenuController@update')->name('admin.menu.update');
        Route::delete('/{model?}/{item_id?}', 'AdminMenuController@destroy')->name('admin.menu.destroy');
        Route::get('/{model?}/{item_id?}/edit', 'AdminMenuController@edit')->name('admin.menu.edit');
    });
});


Route::get('/', 'PageController@index')->name('index');
Route::get('/prices', 'PriceController@index')->name('price.index');
Route::get('/prices/{slug?}', 'PriceController@detail')->name('price.detail');
Route::get('/services', 'ServiceController@index')->name('service.index');
Route::get('/services/{slug?}', 'ServiceController@detail')->name('service.detail');
Route::get('/contacts', 'PageController@contacts')->name('contacts');
Route::post('/contacts', 'PageController@feedback')->name('contacts.feedback');
Route::get('/about', 'PageController@about')->name('about');

// Auth::routes();

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.app_admin')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="jumbotron">
                    <p><span class="label label-primary">Баннеров {{$count_banners ?? ''}}</span></p>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="jumbotron">
                    <p><span class="label label-primary">Преимуществ {{$count_advantages ?? ''}}</span></p>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="jumbotron">
                    <p><span class="label label-primary">Тарифов {{$count_prices ?? ''}}</span></p>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="jumbotron">
                    <p><span class="label label-primary">Услуг {{$count_services ?? ''}}</span></p>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-sm-6">
                <a class="btn btn-block btn-default" href="{{route('admin.banner.create')}}">Создать баннер</a>
                @foreach($banners as $banner)
                    <a class="list-group-item" href="{{route('admin.banner.edit', $banner)}}">
                        <h4 class="list-group-item-heading">{{$banner->title ?? ''}}</h4>
                    </a>
                @endforeach
            </div>
            <div class="col-sm-6">
                <a class="btn btn-block btn-default" href="{{route('admin.advantage.create')}}">Создать преимущество</a>
                @foreach($advantages as $advantage)
                    <a class="list-group-item" href="{{route('admin.advantage.edit', $advantage)}}">
                        <h4 class="list-group-item-heading">{{$advantage->title ?? ''}}</h4>
                    </a>
                @endforeach
            </div>
            <div class="col-sm-6">
                <a class="btn btn-block btn-default" href="{{route('admin.price.create')}}">Создать тариф</a>
                @foreach($prices as $price)
                    <a class="list-group-item" href="{{route('admin.price.edit', $price)}}">
                        <h4 class="list-group-item-heading">{{$price->title ?? ''}}</h4>
                    </a>
                @endforeach
            </div>
            <div class="col-sm-6">
                <a class="btn btn-block btn-default" href="{{route('admin.service.create')}}">Создать услугу</a>
                @foreach($services as $service)
                    <a class="list-group-item" href="{{route('admin.service.edit', $service)}}">
                        <h4 class="list-group-item-heading">{{$service->title ?? ''}}</h4>
                    </a>
                @endforeach
            </div>
        </div>
    </div>
@endsection

resources/views/admin/filter_form.blade.php
@if ($filter_fields)
    <form method="get" action="{{url()->full()}}">
        @php
            $currentRequest = url()->getRequest()->toArray();
        @endphp
        @foreach ($filter_fields as $filter_field)
            @switch($filter_field['type'])
                @case('text')
                    <div class="form-group">
                        <label for="{{$filter_field['name']}}">{{$filter_field['label']}}</label>
                        <input type="text" name="{{$filter_field['name']}}" value="{{$currentRequest[$filter_field['name']]  ?? ''}}" class="form-control" id="{{$filter_field['label']}}" placeholder="{{$filter_field['label']}}">
                    </div>
                    @break
                @case('select')
                    <div class="form-group">
                        <label for="{{$filter_field['name']}}">{{$filter_field['label']}}</label>
                        <select name="{{$filter_field['name']}}" class="form-control" id="{{$filter_field['name']}}">
                            <option value="">Не выбрано</option>
                            @foreach ($filter_field['values'] as $key => $value)
                                <option @if(isset($currentRequest[$filter_field['name']]) && $currentRequest[$filter_field['name']] == $key) selected='selected' @endif value="{{$key}}">{{$value}}</option>
                            @endforeach
                        </select>
                    </div>
                    @break
            @endswitch
        @endforeach
        <a href="{{url()->current()}}" class="btn btn-primary">Сбросить</a>
        <button type="submit" class="btn btn-primary">Поиск</button>
    </form>
@endif

resources/views/admin/sort.blade.php
@if ($sort_fields)
    @php
        $order = (url()->getRequest()->order == "asc") ? "desc" : "asc";
    @endphp
    @foreach ($sort_fields as $sort_field)
        <th>{{$sort_field['label']}} 
        @php
            if (url()->getRequest()->query()) {
                $sort_url = url()->full().'&sort='.$sort_field['name'].'&order='.$order;
            } else {
                $sort_url = url()->current().'?sort='.$sort_field['name'].'&order='.$order;
            }
            $sort = $sort_field['name'];
        @endphp
        @if (!empty(url()->getRequest()->order && $sort == url()->getRequest()->sort))
            @if ($sort == url()->getRequest()->sort && url()->getRequest()->order == "asc")
                <i class="fas fa-sort-amount-down js-sort" data-sort_url="{{ $sort_url }}"></i>
            @endif
            @if ($sort == url()->getRequest()->sort && url()->getRequest()->order == "desc")
                <i class="fas fa-sort-amount-up js-sort" data-sort_url="{{ $sort_url }}"></i>
            @endif
        @else
            <i class="fas fa-frog js-sort" data-sort_url="{{ $sort_url }}"></i>
        @endif
        </th>
    @endforeach
@endif