routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'can:admin-panel']], function() {
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/banner', 'BannerController', ['as' => 'admin']);
    Route::resource('/advantage', 'AdvantageController', ['as' => 'admin']);
    Route::resource('/price', 'PriceController', ['as' => 'admin']);
    Route::resource('/service', 'ServiceController', ['as' => 'admin']);
    Route::group(['prefix' => 'user_managment', 'namespace' => 'UserManagment'], function() {
        Route::resource('/user', 'UserController', ['as' => 'admin.user_managment']);
    });
    Route::group(['prefix' => 'menu', 'namespace' => 'AdminMenu'], function() {
        Route::get('/{model?}', 'AdminMenuController@index')->name('admin.menu.index');
        Route::post('/{model?}', 'AdminMenuController@store')->name('admin.menu.store');
        Route::get('/{model?}/create', 'AdminMenuController@create')->name('admin.menu.create');
        Route::put('/{model?}/{item_id?}', 'AdminMenuController@update')->name('admin.menu.update');
        Route::delete('/{model?}/{item_id?}', 'AdminMenuController@destroy')->name('admin.menu.destroy');
        Route::get('/{model?}/{item_id?}/edit', 'AdminMenuController@edit')->name('admin.menu.edit');
    });
});


Route::get('/', 'PageController@index')->name('index');
Route::get('/prices', 'PriceController@index')->name('price.index');
Route::get('/prices/{slug?}', 'PriceController@detail')->name('price.detail');
Route::get('/services', 'ServiceController@index')->name('service.index');
Route::get('/services/{slug?}', 'ServiceController@detail')->name('service.detail');
Route::get('/contacts', 'PageController@contacts')->name('contacts');
Route::post('/contacts', 'PageController@feedback')->name('contacts.feedback');
Route::get('/about', 'PageController@about')->name('about');

// Auth::routes();

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

app/Price.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Str;
use App\Filters\QueryFilter;

class Price extends Model
{

    protected $fillable = ['title', 'slug', 'description_short', 'description', 'image', 'meta_title', 'meta_description', 'meta_keyword', 'published', 'additional_text', 'image_detail_1', 'image_detail_2', 'show_in_main', 'price', 'h1', 'sort'];
    
    public $pathImages = "public/prices";
    public $pathThumbsImages = "public/thumbnail/prices";
    public $pathStorageImages = "storage/prices";
    public $pathStorageThumbImages = "storage/thumbnail/prices";
    
    // Mutators
    public function setSlugAttribute($value) {
        $this->attributes['slug'] = Str::slug($value);
    }
    
    public function scopeLastPrices($query, $count) {
        return $query->orderBy('created_at', 'desc')->take($count)->get();
    }
    
    public function getThumbImage($nameField) {
        $res = str_replace($this->pathStorageImages, $this->pathStorageThumbImages, $this->{$nameField});
        return $res;
    }
    
    public function scopeFilter(Builder $builder, QueryFilter $filters) {
        return $filters->apply($builder);
    }
}

app/Http/Controllers/Admin/PriceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Price;
use Illuminate\Http\Request;
use App\Filters\PriceFilters;

class PriceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(PriceFilters $filters)
    {
        $breadcrumbs = [
            ['title' => 'Главная', 'url' => route('admin.index')],
            ['title' => 'Тарифы'],
        ];
        $arSortFields = [
            [
                'name' => 'id',
                'label' => '#'
            ],
            [
                'name' => 'title',
                'label' => 'Наименование'
            ],
            [
                'name' => 'published',
                'label' => 'Публикация'
            ]
        ];
        $arFilterFields = [
            [
                'name' => 'id',
                'label' => 'Идентификатор',
                'type' => 'text'
            ],
            [
                'name' => 'title',
                'label' => 'Поиск по названию',
                'type' => 'text'
            ],
            [
                'name' => 'published',
                'label' => 'Публикация',
                'values' => [
                    0 => 'Не опубликовано',
                    1 => 'Опубликовано'
                ],
                'type' => 'select'
            ],
        ];
        return view('admin.prices.index', [
            'breadcrumbs' => $breadcrumbs,
            'filter_fields' => $arFilterFields,
            'sort_fields' => $arSortFields,
            'prices' => Price::filter($filters)->orderBy('created_at', 'desc')->paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $breadcrumbs = [
            ['title' => 'Главная', 'url' => route('admin.index')],
            ['title' => 'Тарифы', 'url' => route('admin.price.index')],
            ['title' => 'Создание тарифа']
        ];
        return view('admin.prices.create', [
            'breadcrumbs' => $breadcrumbs,
            'price' => [],
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'slug' => ['required', 'unique:prices'],
        ]);
        $data = $request->all();
        $model = new Price;
        if ($request->file('image')) {
            $data['image'] = AddFileInDB($request, $model, 'image', ['width' => 80, 'height' => 75]);
        }
        if ($request->file('image_detail_1')) {
            $data['image_detail_1'] = AddFileInDB($request, $model, 'image_detail_1', ['width' => 360, 'height' => 450]);
        }
        if ($request->file('image_detail_2')) {
            $data['image_detail_2'] = AddFileInDB($request, $model, 'image_detail_2', ['width' => 490, 'height' => 300]);
        }
        $price = Price::create($data);
        \Session::flash('success', 'Тариф успешно добавлен!');
        
        return redirect()->route('admin.price.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Price  $price
     * @return \Illuminate\Http\Response
     */
    public function show(Price $price)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Price  $price
     * @return \Illuminate\Http\Response
     */
    public function edit(Price $price)
    {
        $breadcrumbs = [
            ['title' => 'Главная', 'url' => route('admin.index')],
            ['title' => 'Тарифы', 'url' => route('admin.price.index')],
            ['title' => $price->title]
        ];
        if (url()->getRequest()->delete_file && !empty($price->{url()->getRequest()->delete_file})) {
            if (\Storage::delete(str_replace('storage', 'public', $price->{url()->getRequest()->delete_file})) && \Storage::delete(str_replace('storage', \Config::get('constants.path_thumbnail'), $price->{url()->getRequest()->delete_file}))) {
                $price->{url()->getRequest()->delete_file} = "";
                $price->save();
                \Session::flash('success', 'Изображение успешно удалено!');
            }
        }
        return view('admin.prices.edit', [
            'breadcrumbs' => $breadcrumbs,
            'price' => $price,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Price  $price
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Price $price)
    {
        $validator = $request->validate([
            'slug' => [
                'required', 
                \Illuminate\Validation\Rule::unique('prices')->ignore($price->id)
            ],
        ]);
        $data = $request->all();
        if (!isset($data['show_in_main'])) {
            $data['show_in_main'] = false;
        }
        if ($request->file('image')) {
            if ($price->image) {
                DeleteFileFromDB($price, 'image');
            }
            $data['image'] = AddFileInDB($request, $price, 'image', ['width' => 80, 'height' => 75]);
        }

        if ($request->file('image_detail_1')) {
            if ($price->image) {
                DeleteFileFromDB($price, 'image_detail_1');
            }
            $data['image_detail_1'] = AddFileInDB($request, $price, 'image_detail_1', ['width' => 360, 'height' => 450]);
        }
        if ($request->file('image_detail_2')) {
            if ($price->image_detail_2) {
                DeleteFileFromDB($price, 'image_detail_2');
            }
            $data['image_detail_2'] = AddFileInDB($request, $price, 'image_detail_2', ['width' => 490, 'height' => 300]);
        }

        $price->update($data);
        \Session::flash('success', 'Тариф успешно обновлен!');
        
        return redirect()->route('admin.price.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Price  $price
     * @return \Illuminate\Http\Response
     */
    public function destroy(Price $price)
    {
        $price->delete();
        DeleteFileFromDB($price, 'image');
        DeleteFileFromDB($price, 'image_detail_1');
        DeleteFileFromDB($price, 'image_detail_2');
        
        \Session::flash('success', 'Тариф успешно удален!');
        
        return redirect()->route('admin.price.index');
    }
}

app/Http/Controllers/PriceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Price;
use App\Service;

class PriceController extends Controller
{
    
    public function detail($slug) {
        $price = Price::where('slug', $slug)->first();
        if (!$price) {
            abort(404);
        }
        $breadcrumbs = [
            ['title' => 'Главная', 'url' => route('index')],
            ['title' => 'Тарифы', 'url' => route('price.index')],
            ['title' => $price['title']],
        ];
        $services = Service::indexServices(6);
        return view('prices.detail', [
            'breadcrumbs' => $breadcrumbs,
            'price' => $price,
            'services' => $services
        ]);
    }
    
    public function index() {
        $breadcrumbs = [
            ['title' => 'Главная', 'url' => route('index')],
            ['title' => 'Тарифы'],
        ];
        $prices = Price::where('published', 1)->orderBy('created_at', 'desc')->get();
        return view('prices.index', [
            'breadcrumbs' => $breadcrumbs,
            'prices' => $prices
        ]);
    }
    
}

resources/views/admin/prices/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')
    <div class="container">

        @component('admin.components.breadcrumb', ['breadcrumbs' => $breadcrumbs])
            @slot('title') Список тарифов @endslot
        @endcomponent
        
        <hr>
        
        {{ Form::open(['route' => 'admin.price.store', 'class' => 'form-horizontal', 'method' => 'post', 'enctype' => 'multipart/form-data']) }}
            @include('admin.prices.partials.form')
        {{ Form::close() }}
        
    </div>
@endsection

resources/views/admin/prices/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')
    <div class="container">
        @component('admin.components.breadcrumb', ['breadcrumbs' => $breadcrumbs])
            @slot('title') Редактирование тарифа @endslot
        @endcomponent
        
        <hr>

        @if (Session::has('success'))
            <div class="alert alert-success" role="alert">
                {{ Session::get('success') }}
            </div>
        @endif
        
        {{ Form::open(['route' => ['admin.price.update', $price], 'class' => 'form-horizontal', 'method' => 'post', 'enctype' => 'multipart/form-data']) }}
            {{ method_field('PUT') }}
            @include('admin.prices.partials.form')
        {{ Form::close() }}
        
    </div>
@endsection

resources/views/admin/prices/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')
    <div class="container">
        
        @component('admin.components.breadcrumb', ['breadcrumbs' => $breadcrumbs])
            @slot('title') Список тарифов @endslot
        @endcomponent
        
        <hr>
        
        <a href="{{route('admin.price.create')}}" class="btn btn-primary pull-right"><i class="fa fa-plus-square-o"></i> Создать тариф</a>
        @include('admin.filter_form')
        @if (Session::has('success'))
            <div class="alert alert-success" role="alert">
                {{ Session::get('success') }}
            </div>
        @endif
        <table class="table table-striped">
            <thead>
                @include('admin.sort')
                <th class="text-right">Действие</th>
            </thead>
            <tbody>
                @forelse ($prices as $price)
                    <tr>
                        <td>{{$price->id}}</td>
                        <td>{{$price->title}}</td>
                        <td>@if($price->published)Да@elseНет@endif</td>
                        <td class="text-right">
                            <form onsubmit="if(confirm('Удалить?')){ return true; } else { return false; }" action="{{route('admin.price.destroy', $price)}}" method="post">
                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}
                                <a href="{{route('admin.price.edit', ['price' => $price])}}"><i class="fa fa-edit"></i></a>
                                <button type="submit" class="btn"><i class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="{{count($sort_fields)+1}}" class="text-center"><h2>Данные отсутствуют</h2></td>
                    </tr>
                @endforelse
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="{{count($sort_fields)+1}}">
                        <ul class="pagination pull-right">
                            {{$prices->appends(url()->getRequest()->query())->links()}}
                        </ul>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
@endsection